openapi: 3.0.1
info:
  title: Game.Oms.Api.SerialNumberSearch
  description: RESTful API to allow checking if GAME suppied a specific Serial Number or not
  version: v1.0.0
paths:
  /api/Search:
    get:
      tags:
        - Search
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ping'
  '/api/Search/{serialNumber}':
    get:
      tags:
        - Search
      parameters:
        - name: serialNumber
          in: path
          required: true
          schema:
            type: string
            nullable: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SerialNumberDetails'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
components:
  schemas:
    Ping:
      type: object
      properties:
        PingResult:
          type: string
          nullable: true
      additionalProperties: false
    SerialNumberDetails:
      type: object
      properties:
        Id:
          type: integer
          format: int64
        SerialNumber:
          type: string
          nullable: true
        DateAdded:
          type: string
          format: date-time
        Sku:
          type: integer
          format: int32
        ModelReference:
          type: string
          nullable: true
        Validator:
          type: string
          nullable: true
        SkuType:
          type: integer
          format: int32
        SkuTypeName:
          type: string
          nullable: true
        ParentItemSku:
          type: integer
          format: int32
          nullable: true
        OrderDate:
          type: string
          format: date-time
          nullable: true
        StoreNumber:
          type: integer
          format: int32
          nullable: true
        TillNumber:
          type: integer
          format: int32
          nullable: true
        StoreTransactionId:
          type: integer
          format: int32
          nullable: true
        WebOrderNumber:
          type: string
          nullable: true
      additionalProperties: false
    ApiError:
      type: object
      properties:
        Code:
          type: integer
          format: int32
        Description:
          type: string
          nullable: true
      additionalProperties: false